#!/bin/sh

# Create archive
make clean
make release

# Put archive in temp directory
T=$(mktemp -d)
mv *.orig.* $T

# Copy debian directory
git stash
git checkout debian
cp -r debian $T
git checkout -
git stash pop

# Uncompress archive
cd $T
tar -xvvf *.tar.gz
mv debian relational

# Build package
cd relational
dpkg-buildpackage
lintian -E --pedantic ../*.changes

echo $T
