.TH "Relational" 1 "Oct 13, 2011" "Relational algebra learning tool"
.SH "NAME" 
relational \(em Python implementation of Relational algebra. 
.SH "SYNOPSIS" 
.PP 
\fBrelational\fR [OPTIONS\fR\fP] [ FILE .\|.\|.]

.SH "DESCRIPTION" 
.PP 
Python implementation of Relational algebra. This program provides an UI to execute relational algebra queries. It is meant to be used for educational purposes.
 
.SH "OPTIONS" 
.PP 
These programs follow the usual GNU command line syntax, 
with long options starting with two dashes (`\-').  A summary of 
options is included below. However, the ordering is very strict \- 
.IP "\fB-v\fP
Show version information. 

.IP "\fB-h\fP
Shows help.

.IP "\fB-q\fP
Uses the Qt4 GUI (default).

.IP "\fB-r\fP
Uses the readline UI.

.SH "AUTHOR" 
.PP 
This manual page was written by Salvo 'LtWorf' Tomaselli <tiposchi@tiscali.it> for 
the \fBDebian GNU/Linux\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License 
version 3 or any later version published by the Free Software Foundation. 
