.TH "Relational" "1"
.SH "NAME"
relational-cli \(em Implementation of Relational algebra.
.SH "SYNOPSIS"
.PP
\fBrelational-cli\fR [OPTIONS\fR\fP] [ FILE .\|.\|.]

.SH "DESCRIPTION"
.PP
This program provides a command line interface to execute relational algebra queries. It is meant to experiment with relational algebra queries.

.SH "SCRIPTING"
.PP
The tool always runs in interactive mode, but it is possible to write a sequence of queries in a script and run it.

relational-cli < script.txt

The result of all the lines that do not terminate with a `;' are printed.

Comments are lines beginning with `;'.

Whenever stdin or stdout are not a terminal, silent mode will be used, which prints less debug information, to avoid cluttering.

.SH "OPTIONS"
.PP
A summary of options is included below.
.IP "\fB-v\fP
Show version information and exit.

.IP "\fB-h\fP
Shows help and exit.

.IP "\fB-q\fP
Uses the Qt5 GUI.

.IP "\fB-r\fP
Uses the readline UI (default).

.SH "AUTHOR"
.PP
This manual page was written by Salvo 'LtWorf' Tomaselli <tiposchi@tiscali.it> for
the \fBDebian GNU/Linux\fP system (but may be used by others).  Permission is
granted to copy, distribute and/or modify this document under
the terms of the GNU General Public License
version 3 or any later version published by the Free Software Foundation.
