.TH "Relational" "1" 
.SH "NAME" 
relational \(em Python implementation of Relational algebra. 
.SH "SYNOPSIS" 
.PP 
\fBrelational\fR [\-v\fR\fP]
.br
\fBrelational\fR [ FILE .\|.\|.]

.SH "DESCRIPTION" 
.PP 
Python implementation of Relational algebra. This program provides a GUI to execute relational algebra queries. It is meant to be used for educational purposes.
 
.SH "OPTIONS" 
.PP 
These programs follow the usual GNU command line syntax, 
with long options starting with two dashes (`\-').  A summary of 
options is included below. However, the ordering is very strict \- 
.IP "\fB-v\fP
Show version information. 

.SH "AUTHOR" 
.PP 
This manual page was written by Salvo 'LtWorf' Tomaselli <tiposchi@tiscali.it> for 
the \fBDebian GNU/Linux\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License 
version 3 or any later version published by the Free Software Foundation. 
.\" created by instant / docbook-to-man, Fri 10 Oct 2008, 19:02 
