#!/usr/bin/python
import py_compile
import os
for i in os.listdir("/usr/share/python-support/relational/relational/"):
  if i.endswith(".py"):
    py_compile.compile("/usr/share/python-support/relational/relational/"+i)
for i in os.listdir("/usr/share/python-support/relational/relational_gui/"):
  if i.endswith(".py"):
    py_compile.compile("/usr/share/python-support/relational/relational_gui/"+i)
for i in os.listdir("/usr/share/python-support/relational/"):
  if i.endswith(".py"):
    py_compile.compile("/usr/share/python-support/relational/"+i)
